### ISSUE TITLE
Unexpected token m in JSON at position 0

### ISSUE THREAD

**Issue by weiweihuanghuang** [SoNiKBooM/YouSlackBot#1]
Tried to install this today but get this error... ?

```
module.js:674
    throw err;
    ^

SyntaxError: /Users/xxx/.credentials/slackCREDS.json: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/YouSlackBot/node_modules/YouSlackBot/localModules/userList.js:6:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/YouSlackBot/node_modules/YouSlackBot/start.js:7:22)
```

my slackCREDS.json (which I had to create in my /Users/$USER/.credentials folder) looks like this:
```
module.exports =
{
xoxb: 'xoxb-XXXXXXXXXXXXXXXXX...'
}
```

**Comment by glennkentwell** [comment]
Hi,

Because `slackCREDS.json` is a JSON file and not Javascript, it needs to be valid JSON format, which would look like this:

```
{
"xoxb": "xoxb-XXXXXXXXXXXXXXXXX..."
}
```

Note the double quotes around attribute names and values.
